# Generated by Django 5.2.9 on 2025-12-24 04:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'indexes': [models.Index(fields=['name'], name='scraper_com_name_ee5a21_idx')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source_url', models.URLField()),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='scraper.company')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
                'indexes': [models.Index(fields=['title', 'company'], name='scraper_job_title_7408b7_idx'), models.Index(fields=['scraped_at'], name='scraper_job_scraped_8ff27d_idx'), models.Index(fields=['location'], name='scraper_job_locatio_301afb_idx')],
                'constraints': [models.UniqueConstraint(fields=('title', 'company', 'location'), name='unique_job_identifier')],
            },
        ),
    ]
