# Generated by Django 5.2.9 on 2025-12-31 06:59

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_company_name_alter_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
